#pragma once


enum RESULT
{
    RESULT_OK,
    RESULT_API_NOT_OPEN,
    RESULT_OBJECT_INVALID,
    RESULT_ARGUMENT_INVALID,
    RESULT_FUNCTION_INVALID,
    RESULT_SERVICE_INVALID,
    RESULT_COMM_TIMEOUT,
    RESULT_SEE_ERRNO
};

