build-psoc-host-application-arm32v7:
  image: $CI_REGISTRY/docker-images/debian-build-essential:buster-arm32v7
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - uname -m
    - apt-get --no-install-recommends -y install file git libgpiod-dev
    - dpkg -i libdhcom-hal/libdhcom-hal_1.4+deb10-8-g60c22f2_armhf.deb
    - dpkg -i libdhcom-hal/libdhcom-hal-dev_1.4+deb10-8-g60c22f2_armhf.deb
    - mkdir build
    - cd build
    - cmake CMakeLists.txt ../
    - make
    - cpack
    - mv *.deb ../
  artifacts:
    expire_in: 52 weeks
    paths:
      - libpsoc-drc02*.deb
      - psoc-drc02*.deb

build-latex-doc:
  image: $CI_REGISTRY/docker-images/latex:latest
  stage: build
  script:
    - cd C-API/doc
    - doxygen Doxyfile
    - cd latex
    - latexmk -shell-escape -interaction=nonstopmode -pdf -f refman.tex
    - mv refman.pdf ../../../DOC_$CI_PROJECT_NAME.pdf
  artifacts:
    expire_in: 52 weeks
    paths:
      - "DOC_$CI_PROJECT_NAME.pdf"
