#! /bin/sh
# /etc/init.d/json-server
#

### BEGIN INIT INFO
# Provides:          json-server
# Required-Start:    $syslog $time
# Required-Stop:     $syslog $time
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       handle json-server
### END INIT INFO

JSON_SERVER_PATH="/root/json-server"
if [ -f $JSON_SERVER_PATH ]; then

	PID=$(ps -Af | grep $JSON_SERVER_PATH | grep -v grep | cut -c9-14 | tr -d ' ')

	case "$1" in
  	start)
		if [ -z "$PID" ]; then
    			echo -n "==> Executing $JSON_SERVER_PATH ... "
		        $JSON_SERVER_PATH > /dev/null &
        	        echo "done."
		else
    			echo -n "==> $JSON_SERVER_PATH already running, PID $PID.\n"
		fi
		exit 0
    	;;

  	stop)
		if [ -n "$PID" ]; then
    			echo -n "==> Stopping PID $PID ... "
			kill -2 $PID
			echo "done."
		else
    			echo -n "==> $JSON_SERVER_PATH not running.\n"
		fi
		exit 0
    	;;

  	*)
		echo -n "Usage: /etc/init.d/json-server {start|stop}\n"
    		exit 1
    	;;
	esac
else
	echo "json-server not found!\n"
	exit 1
fi

exit 0
